# Generated by Django 4.1.3 on 2022-12-06 11:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trellouser',
            name='last_seen',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, max_length=6, size=None),
        ),
    ]
