# Generated by Django 4.1.3 on 2022-11-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="image",
            field=models.ImageField(blank=True, default=None, null=True, upload_to=""),
        ),
    ]
