# Generated by Django 4.1.3 on 2022-11-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_board_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="checklist",
            field=models.JSONField(blank=True, default={}, null=True),
        ),
    ]
