# Generated by Django 4.1.3 on 2022-12-01 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_card_checklist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="due_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
