# Generated by Django 4.1.3 on 2022-12-01 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_comment_card"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mark",
            name="board",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="marks",
                to="main.board",
            ),
        ),
    ]
