# Generated by Django 4.1.3 on 2022-12-06 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_mark_board'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mark',
            unique_together={('title', 'board')},
        ),
    ]
