# Generated by Django 4.1.3 on 2022-12-07 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_mark_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='checklist',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
